In [84]:
from google.colab import files
files.upload()

Saving boardgames1.csv to boardgames1 (1).csv

In [111]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: category_encoders in /usr/local/lib/python3.7/dist-packages (2.5.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.7.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.10.2)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.21.6)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.5.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.5->category_encoders) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)

In [139]:
!pip install pandas-profiling==3.1.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas-profiling==3.1.0 in /usr/local/lib/python3.7/dist-packages (3.1.0)
Requirement already satisfied: multimethod>=1.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (1.8)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (1.21.6)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (2.11.3)
Requirement already satisfied: htmlmin>=0.1.12 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (0.5.1)
Requirement already satisfied: phik>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (0.12.2)
Requirement already satisfied: tqdm>=4.48.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (4.64.0)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (1.3.5)
Requirement already satisfied: pydantic>=1.8.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (1.9.1)
Requirement already satisfied: markupsafe~=2.0.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (2.0.1)
Requirement already satisfied: requests>=2.24.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (2.28.1)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (0.7.4)
Collecting matplotlib>=3.2.0
  Downloading matplotlib-3.5.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     |████████████████████████████████| 11.2 MB 7.0 MB/s
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (1.7.3)
Requirement already satisfied: tangled-up-in-unicode==0.1.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (0.1.0)
Requirement already satisfied: seaborn>=0.10.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (0.11.2)
Requirement already satisfied: joblib~=1.0.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (1.0.1)
Requirement already satisfied: PyYAML>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.0) (6.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.0) (21.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.0) (2.6.3)
Requirement already satisfied: imagehash in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.0) (4.2.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.0) (7.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.0) (21.3)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.34.4-py3-none-any.whl (944 kB)
     |████████████████████████████████| 944 kB 44.4 MB/s
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.0) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.0) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.0) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.0) (1.4.4)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=3.2.0->pandas-profiling==3.1.0) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling==3.1.0) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling==3.1.0) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.0) (1.24.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.0) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.0) (2022.6.15)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.7/dist-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling==3.1.0) (1.3.0)
Installing collected packages: fonttools, matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.1.1
    Uninstalling matplotlib-3.1.1:
      Successfully uninstalled matplotlib-3.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pdpbox 0.2.1 requires matplotlib==3.1.1, but you have matplotlib 3.5.2 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed fonttools-4.34.4 matplotlib-3.5.2

In [112]:
import pandas as pd
import numpy as np

In [113]:
# 문제 설정 : 게임 별정 평균 'average' 를 높게 받으려면 주의해야할 특성들

In [114]:
df = pd.read_csv('boardgames1.csv')

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 52 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   objectid                20000 non-null  int64
 1   name                    20000 non-null  object
 2   yearpublished           20000 non-null  int64
 3   sortindex               20000 non-null  int64
 4   minplayers              20000 non-null  int64
 5   maxplayers              20000 non-null  int64
 6   minplaytime             20000 non-null  int64
 7   maxplaytime             20000 non-null  int64
 8   minage                  20000 non-null  int64
 9   min_community           14141 non-null  float64
 10  max_community           14803 non-null  float64
 11  totalvotes              20000 non-null  int64
 12  playerage               20000 non-null  object
 13  languagedependence      20000 non-null  int64
 14  usersrated              20000 non-null  int64
 15  average                 20000 non-null  float64
 16  baverage                20000 non-null  float64
 17  stddev                  20000 non-null  float64
 18  avgweight               20000 non-null  float64
 19  numweights              20000 non-null  int64
 20  numgeeklists            20000 non-null  int64
 21  numtrading              20000 non-null  int64
 22  numwanting              20000 non-null  int64
 23  numcomments             20000 non-null  int64
 24  siteviews               20000 non-null  int64
 25  numplays                20000 non-null  int64
 26  numplays_month          20000 non-null  int64
 27  news                    20000 non-null  int64
 28  blogs                   20000 non-null  int64
 29  weblink                 20000 non-null  int64
 30  podcast                 20000 non-null  int64
 31  label                   20000 non-null  object
 32  boardgamedesigner_cnt   20000 non-null  int64
 33  boardgameartist_cnt     20000 non-null  int64
 34  boardgamepublisher_cnt  20000 non-null  int64
 35  boardgamehonor_cnt      20000 non-null  int64
 36  boardgamecategory_cnt   20000 non-null  int64
 37  boardgamemechanic_cnt   20000 non-null  int64
 38  boardgameexpansion_cnt  20000 non-null  int64
 39  boardgameversion_cnt    20000 non-null  int64
 40  boardgamefamily_cnt     20000 non-null  int64
 41  boardgamedesigner       20000 non-null  object
 42  boardgameartist         20000 non-null  object
 43  boardgamepublisher      20000 non-null  object
 44  boardgamehonor          20000 non-null  object
 45  boardgamecategory       20000 non-null  object
 46  boardgameversion        20000 non-null  object
 47  boardgamemechanic       20000 non-null  object
 48  boardgameexpansion      20000 non-null  object
 49  boardgamefamily         20000 non-null  object
 50  description             20000 non-null  object
 51  gamelink                20000 non-null  object
dtypes: float64(6), int64(32), object(14)
memory usage: 7.9+ MB

In [116]:
df.isnull().sum()

objectid                     0
name                         0
yearpublished                0
sortindex                    0
minplayers                   0
maxplayers                   0
minplaytime                  0
maxplaytime                  0
minage                       0
min_community             5859
max_community             5197
totalvotes                   0
playerage                    0
languagedependence           0
usersrated                   0
average                      0
baverage                     0
stddev                       0
avgweight                    0
numweights                   0
numgeeklists                 0
numtrading                   0
numwanting                   0
numcomments                  0
siteviews                    0
numplays                     0
numplays_month               0
news                         0
blogs                        0
weblink                      0
podcast                      0
label                        0
boardgamedesigner_cnt        0
boardgameartist_cnt          0
boardgamepublisher_cnt       0
boardgamehonor_cnt           0
boardgamecategory_cnt        0
boardgamemechanic_cnt        0
boardgameexpansion_cnt       0
boardgameversion_cnt         0
boardgamefamily_cnt          0
boardgamedesigner            0
boardgameartist              0
boardgamepublisher           0
boardgamehonor               0
boardgamecategory            0
boardgameversion             0
boardgamemechanic            0
boardgameexpansion           0
boardgamefamily              0
description                  0
gamelink                     0
dtype: int64

In [117]:
df.describe()
# min 과 max 에서 이상치 확인

,objectid,yearpublished,sortindex,minplayers,maxplayers,minplaytime,maxplaytime,minage,min_community,max_community,...,podcast,boardgamedesigner_cnt,boardgameartist_cnt,boardgamepublisher_cnt,boardgamehonor_cnt,boardgamecategory_cnt,boardgamemechanic_cnt,boardgameexpansion_cnt,boardgameversion_cnt,boardgamefamily_cnt
count,20000.00000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.00000,20000.000000,14141.000000,14803.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,88667.61500,1981.268700,10000.500000,2.055250,5.59215,68.096450,94.28945,9.476350,3.203522,4.277917,...,1.943050,1.339200,1.379250,2.500100,0.436000,2.568050,2.306900,1.185750,3.392800,1.429500
std,90640.91959,219.223277,5773.647028,0.745537,15.04921,466.502106,1005.75196,3.738842,1.398935,2.155624,...,7.956222,0.787003,4.768926,5.082961,1.609824,1.366515,1.707764,6.809425,12.317236,1.728375
min,1.00000,-3500.000000,1.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5858.75000,1997.000000,5000.750000,2.000000,4.00000,20.000000,30.00000,8.000000,2.000000,3.000000,...,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,1.000000,0.000000,1.000000,0.000000
50%,39278.50000,2008.000000,10000.500000,2.000000,4.00000,30.000000,45.00000,10.000000,3.000000,4.000000,...,0.000000,1.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.000000,2.000000,1.000000
75%,169680.50000,2015.000000,15000.250000,2.000000,6.00000,60.000000,90.00000,12.000000,4.000000,5.000000,...,1.000000,2.000000,2.000000,2.000000,0.000000,3.000000,3.000000,0.000000,3.000000,2.000000
max,295770.00000,2021.000000,20000.000000,10.000000,999.00000,60000.000000,120000.00000,25.000000,31.000000,31.000000,...,577.000000,21.000000,508.000000,174.000000,50.000000,14.000000,18.000000,444.000000,1002.000000,86.000000

In [118]:
# 보드게임의 첫 출시는 UNO 로 1971년에 출시됐다
# 데이터에 1971년 이전에 발매됐다고 표시된게 2만개중 750개의 데이터이며 이는 무시할 수 없는 개수이므로 1971년 이전에 출시된 데이터에 결측값을 넣어준 후 평균을 구하고 평균값을 넣어줬습니다.

df.loc[df["yearpublished"]<1971 , "yearpublished"] = np.nan
df['yearpublished'].mean()

2005.370181818182

In [119]:
df['yearpublished'].fillna(2005,inplace=True)

In [120]:
# objectid 와 sortindex 의 성능이 겹치므로 objectid 열을 삭제
df.drop(['objectid'],axis=1,inplace=True)
# 단 하나의 unique 한 값을 가진 label 열을 삭제
df.drop(['label'],axis=1,inplace=True)

In [121]:
# min_community 와 max_community 는 각각 커뮤니티 내에서 구한 평균 최소, 최대 플레이어이다. 그렇기 때문에 비인기 보드게임은 결측값이 존재한다.
# 그러므로 minplayers	maxplayers 는 publisher 가 정해준 최소, 최대 플레이어이므로 결측값을 채워줍니다.

df.loc[df['min_community'].isna(),['min_community']] = df['minplayers']
df.loc[df['max_community'].isna(),['max_community']] = df['maxplayers']

In [122]:
# playerage 열 정제
# playerage 는 각각 커뮤니티 내에서 해당 보드게임을 플레이한 유저들의 최저 연령이다. 그러므로 결측값에 publisher가 정해준 값을 채워줍니다.
df['playerage'].unique()

array(['14', '12', '10', '18', '8', '6', '16', '5', '4', '3',
       '(no votes)', '4\\u201310', '3\\u201310', '4\\u201312',
       '6\\u201312', '3\\u201312', '5\\u201312', '2\\u20134', '2',
       '10\\u201314', '8\\u201310', '8\\u201316', '2\\u20135',
       '5\\u201310', '10\\u201316', '12\\u201314', '10\\u201312',
       '3\\u20136', '3\\u20138', '4\\u20138', '12\\u20132', '8\\u201314',
       '6\\u201310', '8\\u201312', '4\\u201314', '5\\u201314',
       '16\\u201318', '6\\u201316', '6\\u201314', '10\\u201318',
       'Up to 8', '10\\u20138', '12\\u201316', '21 and up', 'Up to 14',
       '4\\u201316', '6\\u20138', 'Up to 10', '4\\u20136', '16\\u201314',
       '2\\u20138', '5\\u20138', '5\\u201316', '14\\u201316', '3\\u20135',
       'All ages', 'Up to 6', '12\\u201318', 'Up to 5', '10\\u20132',
       '2\\u201312', '16\\u20135', '3\\u201314', '8\\u201318',
       '6\\u201318', '2\\u20133', '2\\u20136', '5\\u201318', 'Up to 12',
       '2\\u201310', '3\\u20134', '14\\u201318', '21 and up\\u20132',
       '5\\u20136', '3\\u20132', '18\\u20134'], dtype=object)

In [123]:
df['playerage'] = df['playerage'].str.replace('\\','', regex=True)
df['playerage'] = df['playerage'].str.replace(' and up','', regex=True)
df['playerage'] = df['playerage'].str.replace('Up to ','', regex=True)
tmp = df['playerage'].str.split('u',expand=True)
df['playerage'] = tmp[0]

In [124]:
df.loc[df['playerage']=='(no votes)',['playerage']] = df['minage']
df.loc[df['playerage']=='All ages',['playerage']] = df['minage']
df['playerage'] = df['playerage'].astype(int)

In [125]:
# 범주형 특성들이 데이터가 높은 카디널리티를 가지고 있어 수정하지 않습니다.

In [ ]:
'''
tmp1 = df['boardgamecategory'].str.split(',',expand=True)
tmp1[0] = tmp1[0].str.replace('[', '', regex=True)
tmp1[0] = tmp1[0].str.replace(']', '', regex=True)
tmp1[0] = tmp1[0].str.replace("'", '', regex=True)
tmp1[0] = tmp1[0].str.replace("/", '', regex=True)
tmp1[0]
tmp1.describe(exclude='number').T.sort_values(by='unique')
'''

In [126]:
# 데이터를 정제하고도 높은 카디널리티를 유지해 인코딩이 힘들것으로 판단되고
# 범주형 열을 ordinal encoding를 했을 때 생길 count 열이 이미 존재하므로 삭제
df.describe(exclude='number').T.sort_values(by='unique')

,count,unique,top,freq
boardgamehonor,20000,2582,['None'],16482
boardgameexpansion,20000,4305,['None'],15455
boardgamecategory,20000,6401,['Card Game'],938
boardgamemechanic,20000,6456,['Hexagon Grid'],871
boardgameversion,20000,7893,['First edition'],7437
boardgamedesigner,20000,8552,"['(Uncredited)""']",1743
boardgamefamily,20000,9746,['First edition'],2084
boardgamepublisher,20000,10006,['GMT Games'],214
boardgameartist,20000,10794,['(Uncredited)'],1757
name,20000,19546,Warhammer 40,20
description,20000,19985,"Dice Throne is a game of intriguing dice, tact...",4
gamelink,20000,20000,/boardgame/174430/gloomhaven,1

In [128]:
#  범주형 컬럼 삭제
df.drop(df.describe(exclude='number'),axis=1,inplace=True)

ValueError: ignored

In [129]:
# 회귀모델 적용후 특성찾기

In [130]:
df

,yearpublished,sortindex,minplayers,maxplayers,minplaytime,maxplaytime,minage,min_community,max_community,totalvotes,...,podcast,boardgamedesigner_cnt,boardgameartist_cnt,boardgamepublisher_cnt,boardgamehonor_cnt,boardgamecategory_cnt,boardgamemechanic_cnt,boardgameexpansion_cnt,boardgameversion_cnt,boardgamefamily_cnt
0,2017.0,1,1,4,60,120,12,3.0,4.0,827,...,139,1,3,9,23,5,12,4,19,7
1,2015.0,2,2,4,60,60,13,4.0,4.0,549,...,164,2,1,11,20,2,8,0,33,3
2,2016.0,3,1,5,120,120,12,3.0,4.0,1252,...,148,1,1,20,20,6,9,15,29,6
3,2015.0,4,2,4,120,120,14,3.0,4.0,436,...,42,1,4,13,3,3,5,1,14,2
4,2018.0,5,2,4,60,120,14,3.0,4.0,242,...,21,3,3,8,6,3,8,0,9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,1990.0,19996,2,8,90,90,0,2.0,8.0,0,...,0,1,0,1,0,2,2,0,0,1
19996,1988.0,19997,2,2,20,20,0,2.0,2.0,0,...,0,1,0,1,0,1,1,0,0,1
19997,1972.0,19998,2,4,20,20,5,2.0,4.0,0,...,0,1,1,3,0,2,1,0,3,0
19998,1989.0,19999,2,2,30,30,6,2.0,2.0,0,...,0,1,0,2,0,2,1,0,1,1
19999,1988.0,20000,2,2,20,20,0,2.0,2.0,2,...,0,1,0,1,0,1,2,0,1,0

In [131]:
df['average'] = df['average'].astype(int) # 모델 적용을 위해 실수형 -> 정수형 변환

In [132]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, random_state=2)

In [133]:
train, val = train_test_split(train, random_state=2)

In [134]:
target = 'average'

In [135]:
features = train.drop(columns=[target]).columns

In [137]:
X_train = train[features]
y_train = train[target]
X_val = val[features]
y_val = val[target]
X_test = test[features]
y_test = test[target]

In [138]:
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

pipe = make_pipeline(
    DecisionTreeClassifier(max_depth=3,random_state=1)
)

pipe.fit(X_train, y_train)
from sklearn.metrics import f1_score
predict = pipe.predict(X_val)
f1=f1_score(y_val, predict, average='micro')
print("F1 score: {}" .format(f1))

F1 score: 0.6336

In [141]:
import matplotlib.pyplot as plt